server:
  port: 8011
<<<<<<< HEAD
countrystatecity:
  forceUpdate: false
=======

  error:
    include-message: always
    include-binding-errors: on_param
    include-stacktrace: never
    include-exception: false

>>>>>>> main
spring:
  profiles:
    active: prod
  application:
    name: ea-course-registration
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://us-cdbr-east-05.cleardb.net:3306/heroku_16699266ca49cba
    username: bdec61cbf0420f
    password: d13dd415
    hikari:
      maximumPoolSize: 10
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update

security:
  jwt:
    secretkey: secret-key
    timeout-millis: 3600000 #1 hr
