server:
  port: 8010
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: never
    include-exception: false

spring:
  datasource:
    url: 'jdbc:postgresql://localhost:5432/cs544'
    username: 'root'
    password: 'CS544-EA'
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 5

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop