server:
  port: 8011
  error:
    include-message: always
    include-binding-errors: on_param
    include-stacktrace: never
    include-exception: false
spring:
  profiles:
    active: dev
  application:
    name: ea-course-registration
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://us-cdbr-east-05.cleardb.net:3306/heroku_1ca686ea640d958
    username: be4721dffdca39
    password: b31cad21
    hikari:
      maximumPoolSize: 1000
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        properties:
          hibernate:
            dialect: org.hibernate.dialect.MySQL8Dialect
  main:
    allow-bean-definition-overriding: true

security:
  jwt:
    secretkey: secret-key
    timeout-millis: 3600000 #1 hr
