server:
  port: 8011
countrystatecity:
  forceUpdate: false
spring:
  application:
    name: EA Final Project (Dev)
  datasource:
    url: jdbc:mysql://localhost:3306/ea544
    username: root
    password:
  jpa:
    show-sql: true