server:
  port: 8010
countrystatecity:
  forceUpdate: false
spring:
  application:
    name: EA Final Project (Dev)
  datasource:
    url: jdbc:mysql://localhost:3306/cs544
    username: root
    password: P@ssw0rd